name: Documentation

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write

jobs:
  build_and_deploy_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: "pyproject.toml"

      - name: Install self with documentation extras
        run: python -m pip install ".[docs]"

      - name: Build HTML documentation with sphinx
        run: sphinx-build -W -b html docs docs/_build/html

      - name: Publish documentation on GitHub pages
        #if: success() && github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/_build/html
          branch: gh-pages
          git-config-name: "github-actions[bot]"
          git-config-email: "github-actions[bot]@users.noreply.github.com"
